services:
  - type: web
    name: theorie-moerad
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: theorie-moerad-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        sync: false

databases:
  - name: theorie-moerad-db
    databaseName: theorie_moerad
    user: theorie_moerad_user
    plan: free
    region: frankfurt
